### ISSUE TITLE
NotImplementedError: The image and the kernel must have the same type.inputs(float32), kerns(float64)

### ISSUE THREAD

**Issue by riokt** [saebrahimi/RATM#2]
I got this error while running using kth dataset
> Traceback (most recent call last):
>   File "train_attention_rnn_on_kth.py", line 97, in <module>
>     theano_rng=theano_rng, batchsize=batchsize)
>   File "/home/rizqi-okta/Documents/tracker/RATM/kth/convnet_eth_inria_data/cnn.py", line 126, in __init__
>     self.probabilities = self.forward(self.inputs)
>   File "/home/rizqi-okta/Documents/tracker/RATM/kth/convnet_eth_inria_data/cnn.py", line 149, in forward
>     layer_outp = layer.forward(inputs)
>   File "../common/layers.py", line 121, in forward
>     image_shape=padded_inputs_shape)
>   File "/home/rizqi-okta/miniconda2/envs/tracker/lib/python2.7/site-packages/theano/tensor/nnet/conv.py", line 153, in conv2d
>     return op(input, filters)
>   File "/home/rizqi-okta/miniconda2/envs/tracker/lib/python2.7/site-packages/theano/gof/op.py", line 615, in __call__
>     node = self.make_node(*inputs, **kwargs)
>   File "/home/rizqi-okta/miniconda2/envs/tracker/lib/python2.7/site-packages/theano/tensor/nnet/conv.py", line 655, in make_node
>     "inputs(%s), kerns(%s)" % (_inputs.dtype, _kerns.dtype))
> NotImplementedError: The image and the kernel must have the same type.inputs(float32), kerns(float64)

**Comment by vmichals** [comment]
For some reason the kernels are not float32. 
We have the following entry in our _~/.theanorc_, that should take care of this issue (float values are automatically cast to 32bit precision):
```
[global]
floatX = float32
```
Please let us know, if that helped.

**Comment by Ming-Du** [comment]
you can try to fix the code in attention_rnn.py  about 59 lines, to replace ftensor4 with ftensor5, then you can fix this error
